'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { Button, Card, CardContent, Input, Label, LoadingState } from '@rademics/ui';
import { apiFetch, ApiError } from '@/lib/api';

interface AssignableProject {
  id: string;
  number: number;
  code: string;
  name: string;
  status: string;
}

/**
 * One-step client onboarding: name, email, and tick the projects they get.
 *
 * Projects are picked from a list rather than typed as codes. The code is
 * generated by the system and no one memorises RAD-007, so asking a human to
 * reproduce it only creates the one mistake that matters here — giving a client
 * another client's project. The list shows only projects not already bound to a
 * client, which makes the wrong answer unreachable rather than merely rejected.
 *
 * The client organization is created server-side from the client's own name. It
 * is real — the portal refuses entry without one, invoices hang off it, and
 * deactivating it is the kill switch that ends access — but it is not a decision
 * worth asking for.
 */
export default function NewClientPage() {
  const router = useRouter();
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [projects, setProjects] = useState<AssignableProject[] | null>(null);
  const [picked, setPicked] = useState<Set<number>>(new Set());
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    apiFetch<AssignableProject[]>('/client-orgs/assignable-projects')
      .then(setProjects)
      .catch(() => setProjects([]));
  }, []);

  function toggle(number: number) {
    setPicked((prev) => {
      const next = new Set(prev);
      if (next.has(number)) next.delete(number);
      else next.add(number);
      return next;
    });
  }

  const canSubmit = Boolean(name.trim() && email.trim()) && picked.size > 0 && !saving;

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    setError(null);
    setSaving(true);
    try {
      await apiFetch('/client-orgs/onboard', {
        method: 'POST',
        body: JSON.stringify({
          name: name.trim(),
          email: email.trim(),
          projectNumbers: [...picked],
        }),
      });
      router.push('/clients');
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Could not create the client');
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className="mx-auto max-w-xl">
      <div className="mb-4">
        <Link href="/clients" className="text-sm text-slate-500 hover:text-slate-800">
          ← Back to Clients
        </Link>
      </div>
      <h1 className="text-xl font-semibold text-slate-800">New client</h1>
      <p className="mt-1 text-sm text-slate-500">
        They get a portal login and see only the projects you tick here.
      </p>

      <Card className="mt-4">
        <CardContent className="pt-6">
          <form onSubmit={submit} className="flex flex-col gap-4">
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="name">Client name</Label>
              <Input
                id="name"
                placeholder="Enter the client's name"
                value={name}
                onChange={(e) => setName(e.target.value)}
                required
                minLength={2}
                maxLength={150}
              />
            </div>

            <div className="flex flex-col gap-1.5">
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                type="email"
                placeholder="Enter their email address"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
              />
              <p className="text-xs text-slate-400">Their portal login. They&apos;ll be emailed an invite.</p>
            </div>

            <div className="flex flex-col gap-1.5">
              <Label>Which projects can they see?</Label>
              {projects === null ? (
                <LoadingState />
              ) : projects.length === 0 ? (
                <div className="rounded-md border border-slate-200 bg-slate-50 px-3 py-3 text-sm text-slate-500">
                  Every project already belongs to a client. Create a project first, then come back.
                </div>
              ) : (
                <div className="flex max-h-64 flex-col divide-y divide-slate-100 overflow-y-auto rounded-md border border-slate-200">
                  {projects.map((p) => (
                    <label
                      key={p.id}
                      className="flex cursor-pointer items-center gap-3 px-3 py-2.5 text-sm hover:bg-slate-50"
                    >
                      <input
                        type="checkbox"
                        checked={picked.has(p.number)}
                        onChange={() => toggle(p.number)}
                        className="h-4 w-4 shrink-0 rounded border-slate-300 text-accent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent"
                      />
                      <span className="font-mono text-xs text-slate-400">{p.code}</span>
                      <span className="min-w-0 flex-1 truncate text-slate-800">{p.name}</span>
                    </label>
                  ))}
                </div>
              )}
              <p className="text-xs text-slate-400">
                Only projects not already given to another client are listed.
              </p>
            </div>

            {error ? <p className="text-sm text-slate-900">{error}</p> : null}

            <div className="flex gap-3">
              <Button type="submit" disabled={!canSubmit}>
                {saving ? 'Creating…' : 'Create client'}
              </Button>
              <Link href="/clients">
                <Button type="button" variant="outline">
                  Cancel
                </Button>
              </Link>
            </div>

            {picked.size > 0 ? (
              <p className="text-xs text-slate-400">
                {name.trim() || 'This client'} will see{' '}
                {picked.size === 1 ? '1 project' : `${picked.size} projects`}.
              </p>
            ) : null}
          </form>
        </CardContent>
      </Card>
    </div>
  );
}
